[package]
name = "bacup"
version = "0.1.0"
authors = ["Paolo Galeone <me@pgaleone.eu>"]
edition = "2018"
repository = "https://github.com/galeone/bacup"
default-run = "server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.48"
chrono = "0.4.19"
flate2 = "1.0.20"
futures = "0.3.13"
log = "0.4.14"
rust-s3 = "0.26.4"
serde = { version = "1.0.124", features = ["derive"] }
snafu = "0.6.10"
stderrlog = "0.5.1"
structopt = "0.3.21"
tar = "0.4.33"
toml = "0.5.8"
url = { version = "2.2.1", features = ["serde"] }
